"""Email delivery service for sending digests via SMTP."""

import asyncio
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional
from datetime import datetime

import structlog

from ..config import settings
from ..models.db import Digest
from ..services.database import build_engine, create_session_factory, session_scope

logger = structlog.get_logger()


def format_digest_email(digest: Digest) -> str:
    """Format digest content as HTML email."""
    content = digest.content_json
    
    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
            h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
            h2 {{ color: #34495e; margin-top: 30px; }}
            .intro {{ background: #ecf0f1; padding: 15px; border-radius: 5px; margin: 20px 0; }}
            .cluster {{ background: #fff; border-left: 4px solid #3498db; padding: 15px; margin: 20px 0; }}
            .cluster-title {{ font-weight: bold; color: #2980b9; }}
            .articles {{ margin-top: 10px; }}
            .article {{ margin: 8px 0; }}
            .article a {{ color: #2980b9; text-decoration: none; }}
            .article a:hover {{ text-decoration: underline; }}
            .meta {{ color: #7f8c8d; font-size: 0.9em; margin-top: 10px; }}
            .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #bdc3c7; color: #7f8c8d; font-size: 0.85em; }}
        </style>
    </head>
    <body>
        <h1>{'🤖' if digest.persona == 'genai' else '🚀'} {digest.persona.replace('_', ' ').title()} Digest</h1>
        <p class="meta">Generated: {digest.generated_at.strftime('%B %d, %Y at %I:%M %p')}</p>
        
        <div class="intro">
            <p>{content['intro']}</p>
        </div>
    """
    
    for section in content['sections']:
        html += f"""
        <div class="cluster">
            <div class="cluster-title">{section['theme']}</div>
            <p class="meta">{section['article_count']} articles, avg relevance: {section['avg_score']:.2f}</p>
            <p>{section['summary']}</p>
            
            <div class="articles">
                <strong>Articles:</strong>
                <ul>
        """
        for article in section['articles']:
            html += f"""<li class="article"><a href="{article['url']}" target="_blank">{article['title']}</a></li>"""
        
        html += """
                </ul>
            </div>
        </div>
        """
    
    html += f"""
        <div class="footer">
            <p>Total: {content['total_articles']} articles across {content['total_clusters']} topics</p>
            <p>This digest was automatically generated by DailyDigest.</p>
        </div>
    </body>
    </html>
    """
    
    return html


def send_email(
    to_email: str,
    subject: str,
    html_content: str,
    smtp_host: Optional[str] = None,
    smtp_port: Optional[int] = None,
    smtp_username: Optional[str] = None,
    smtp_password: Optional[str] = None,
    from_email: Optional[str] = None,
) -> None:
    """Send email via SMTP."""
    # Use provided values or fall back to settings
    smtp_host = smtp_host or settings.smtp_host
    smtp_port = smtp_port or settings.smtp_port
    smtp_username = smtp_username or settings.smtp_username
    smtp_password = smtp_password or settings.smtp_password
    from_email = from_email or settings.smtp_from_email
    
    if not all([smtp_host, smtp_port, smtp_username, smtp_password, from_email]):
        raise ValueError("SMTP configuration incomplete. Check .env file.")
    
    # Create message
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = from_email
    msg['To'] = to_email
    
    # Attach HTML content
    html_part = MIMEText(html_content, 'html')
    msg.attach(html_part)
    
    # Send email
    try:
        if settings.smtp_use_tls:
            with smtplib.SMTP(smtp_host, smtp_port) as server:
                server.starttls()
                server.login(smtp_username, smtp_password)
                server.send_message(msg)
        else:
            with smtplib.SMTP_SSL(smtp_host, smtp_port) as server:
                server.login(smtp_username, smtp_password)
                server.send_message(msg)
        
        logger.info("email_sent", to=to_email, subject=subject)
    except Exception as e:
        logger.error("email_send_failed", error=str(e), to=to_email)
        raise


def send_digest_email(digest_id: str, to_email: str) -> None:
    """Send a digest via email."""
    engine = build_engine(settings.database_url)
    session_factory = create_session_factory(engine)
    
    with session_scope(session_factory) as session:
        digest = session.query(Digest).filter(Digest.id == digest_id).first()
        
        if not digest:
            raise ValueError(f"Digest not found: {digest_id}")
        
        # Format email
        html_content = format_digest_email(digest)
        subject = f"{digest.persona.replace('_', ' ').title()} Digest - {digest.generated_at.strftime('%b %d, %Y')}"
        
        # Send email
        send_email(
            to_email=to_email,
            subject=subject,
            html_content=html_content,
        )
        
        logger.info("digest_emailed", digest_id=digest_id, persona=digest.persona, to=to_email)
